sim:
	iverilog -o ../sqrt_u32 ../../src/*v                                                                  
	
wave:
	iverilog -o ../sqrt_u32 ../../src/*v                                                                  
	../sqrt_u32
	gtkwave ../sqrt_u32_tb.vcd
