sim:
	iverilog -o ../sort_32_u8 ../../src/*v                                                                  
	
wave:
	iverilog -o ../sort_32_u8 ../../src/*v
	../sort_32_u8
	gtkwave ../sort_32_u8_tb.vcd
